source ~/.bash_prompt
source ~/.git-completion.bash

alias gs="git status"
alias ga="git add -A"
alias gl="git log"
alias gr="git reset HEAD"
alias gd="git diff"
alias gps="git push"
alias gpl="git pull"
alias gc="git commit -m"

