source ~/.bash_prompt
source ~/.git-completion.bash

    #######
#---# Git #---#
    #######

alias gs="git status"
alias ga="git add -A"
alias gl="git log"
alias gr="git reset HEAD"
alias gd="git diff"
alias gdc="git diff --cached"
alias gps="git push"
alias gpl="git pull"
alias gc="git commit -m"
alias gb="git branch"
alias gbm="git branch -m"
alias gplom="git pull origin master"
alias gpom="git push origin master"
alias gsl="git stash list"
alias gca="git commit --amend"
alias gch="git checkout"
alias gco="git checkout"
alias gck="git checkout"
alias gr="git rebase -i"
alias grc="git rebase --continue"
alias gcl="git clean -f"
alias grh="git reset HEAD"
alias gap="git add -p"
alias gcp="git cherry-pick"

__git_complete gb _git_branch
__git_complete gch _git_checkout
__git_complete gco _git_checkout
__git_complete gck _git_checkout

    ########
#---# Brew #---#
    ########

alias bd="brew doctor"

    ########
#---# Misc #---#
    ########

alias m="make"
alias mc="make && make clean"
alias mr="make && ./myprogram"

