set background=dark
set autoindent
filetype plugin indent on
set shiftwidth=4
set softtabstop=4
set expandtab
set number
set shiftwidth=4
set expandtab
set showmatch
set cul
hi CursorLine term=none cterm=none ctermbg=235
:highlight LineNr ctermfg=green
set smarttab
set scrolloff=5
set showcmd
set hidden

ca WQ wq
ca Wq wq

" Move lines up and down
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==

inoremap <C-j> <ESC>:m .+1<CR>==gi
inoremap <C-k> <ESC>:m .-2<CR>==gi

vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

