set background=dark
set autoindent
filetype plugin indent on
set shiftwidth=4
set softtabstop=4
set expandtab
set number
set shiftwidth=4
set expandtab
set showmatch
set cul
hi CursorLine term=none cterm=none ctermbg=235
:highlight LineNr ctermfg=green
set smarttab
set scrolloff=5

