""" General
set autoindent
set smartindent
filetype plugin indent on

set smarttab
set shiftwidth=4
set softtabstop=4
set expandtab
set shiftwidth=4
set expandtab

set number
set showmatch
set cul
set scrolloff=5
set showcmd
set hidden

""" Remap some common annoying errors
ca WQ wq
ca Wq wq
ca W w
ca Q q

""" Move lines up and down with C-j/k
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==
inoremap <C-j> <ESC>:m .+1<CR>==gi
inoremap <C-k> <ESC>:m .-2<CR>==gi
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv

""" Always strip strailing whitespace on save
autocmd BufWritePre * :%s/\s\+$//e

""" Colors
syntax enable
set t_Co=256
colorscheme wombat256mod
hi Normal ctermbg=NONE
hi CursorLine term=none cterm=none ctermbg=232

set backspace=indent,eol,start

"set nocompatible
"filetype off

"set rtp+=~/.vim/bundle/Vundle.vim
"call vundle#begin()

"Plugin 'gmarik/Vundle.vim'
"Plugin 'Valloric/YouCompleteMe'

"call vundle#end()

"filetype plugin indent on

